/* YunaRunes monster catalog. Data is deliberately structured so real monster art/data can be added without changing the UI. */
(function(){
  const monsters=[
    {name:'Veromos',family:'Ifrit',element:'Dark',awakening:'2A',emoji:'👹',sets:['Violent','Focus'],slots:['SPD','HP%','HP%'],stats:['HP','DEF','SPD','ACC'],use:'PvE / suporte',skills:['Dark Strike','Conversion','Beneficial Effect Removal']},
    {name:'Bella',family:'Inugami',element:'Light',awakening:'2A',emoji:'🐺',sets:['Swift','Energy'],slots:['SPD','HP%','HP%'],stats:['SPD','HP','DEF','ACC'],use:'PvE / suporte',skills:['Scratch','Defense Break','Heal & Cleanse']},
    {name:'Raoq',family:'Inugami',element:'Fire',awakening:'2A',emoji:'🐺',sets:['Fatal','Blade'],slots:['ATK%','ATK%','ATK%'],stats:['ATK','CR','CD','SPD'],use:'PvE / early game',skills:['Scratch','Team Up','Extra Turn']},
    {name:'Loren',family:'Cow Girl',element:'Light',awakening:'2A',emoji:'🏹',sets:['Swift','Focus'],slots:['SPD','HP%','HP%'],stats:['SPD','HP','ACC','DEF'],use:'PvE / bosses',skills:['Cross Fire','Wild Shot','Defense Break / ATB Control']},
    {name:'Fran',family:'Fairy Queen',element:'Light',awakening:'2A',emoji:'🧚',sets:['Swift','Energy'],slots:['SPD','HP%','HP%'],stats:['SPD','HP','DEF','ACC'],use:'PvE / suporte',skills:['Light Fairy Blessing','Heal','Immunity']},
    {name:'Megan',family:'Mystic Witch',element:'Water',awakening:'2A',emoji:'🧙',sets:['Swift','Focus'],slots:['SPD','HP%','HP%'],stats:['SPD','HP','ACC','DEF'],use:'PvE / Arena',skills:['Essence Drain','Toad Poison','ATB Boost']}
  ];
  const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function mount(){
    if(document.querySelector('.yuna-runes-shell'))return;
    const anchor=document.querySelector('main')||document.querySelector('.container')||document.body;
    const shell=document.createElement('section');shell.className='yuna-runes-shell';shell.id='yunarunes';
    shell.innerHTML=`<div class="yuna-runes-head"><div><div class="yuna-runes-title">YunaRunes — Monster Builds</div><div class="yuna-runes-sub">Pesquisa monstros, segundo despertar e builds de runas.</div></div><input class="yuna-runes-search" placeholder="Pesquisar monstro, família ou elemento..." aria-label="Pesquisar monstro"></div><div class="yuna-runes-filters">${['Todos','Fire','Water','Wind','Light','Dark'].map((x,i)=>`<button class="yuna-runes-filter ${i===0?'active':''}" data-filter="${x}">${x}</button>`).join('')}</div><div class="yuna-runes-grid"></div><div class="yuna-detail"></div>`;
    anchor.appendChild(shell);
    const grid=shell.querySelector('.yuna-runes-grid'),detail=shell.querySelector('.yuna-detail'),search=shell.querySelector('.yuna-runes-search');let filter='Todos';
    function render(){const q=search.value.toLowerCase().trim();const list=monsters.filter(m=>(filter==='Todos'||m.element===filter)&&(!q||`${m.name} ${m.family} ${m.element}`.toLowerCase().includes(q)));grid.innerHTML=list.map((m,i)=>`<article class="yuna-monster-card" data-i="${monsters.indexOf(m)}"><div class="yuna-monster-art">${m.emoji}</div><div class="yuna-monster-name">${esc(m.name)}</div><div class="yuna-monster-family">${esc(m.family)}</div><div class="yuna-monster-meta"><span class="yuna-chip">${esc(m.element)}</span><span class="yuna-chip">${esc(m.awakening)}</span></div></article>`).join('')||'<div style="color:#aaa0b9;padding:20px">Nenhum monstro encontrado.</div>';}
    function open(m){detail.classList.add('open');detail.innerHTML=`<div class="yuna-detail-top"><div class="yuna-detail-art">${m.emoji}</div><div><h2>${esc(m.name)}</h2><p style="color:#aaa0b9;margin-top:5px">${esc(m.family)} · ${esc(m.element)} · ${esc(m.awakening)}</p><div class="yuna-awakenings"><span class="yuna-awakening active">Normal</span><span class="yuna-awakening">2º Despertar</span></div><p style="color:#d0c6d9;margin-top:12px">Uso recomendado: ${esc(m.use)}</p></div></div><div class="yuna-tabs"><button class="yuna-tab active" data-tab="overview">Overview</button><button class="yuna-tab" data-tab="runes">Runes</button><button class="yuna-tab" data-tab="skills">Skills</button></div><div class="yuna-tab-content active" data-content="overview"><div class="yuna-stats">${m.stats.map(x=>`<span class="yuna-stat"><b>${esc(x)}</b> prioridade</span>`).join('')}</div></div><div class="yuna-tab-content" data-content="runes"><div class="yuna-rune-build">${m.sets.map((s,i)=>`<div class="yuna-rune-slot"><b>${esc(s)} set</b><span>Slot ${i===0?'2':'4/6'}: ${esc(m.slots[i]||'HP%')}</span><span>Substats: SPD · HP% · DEF% · ACC</span></div>`).join('')}</div></div><div class="yuna-tab-content" data-content="skills"><div class="yuna-stats">${m.skills.map(x=>`<span class="yuna-stat">${esc(x)}</span>`).join('')}</div></div>`;detail.querySelectorAll('.yuna-tab').forEach(b=>b.onclick=()=>{detail.querySelectorAll('.yuna-tab,.yuna-tab-content').forEach(x=>x.classList.remove('active'));b.classList.add('active');detail.querySelector(`[data-content="${b.dataset.tab}"]`).classList.add('active')});detail.scrollIntoView({behavior:'smooth',block:'nearest'});}
    grid.onclick=e=>{const c=e.target.closest('.yuna-monster-card');if(c)open(monsters[+c.dataset.i])};shell.querySelectorAll('.yuna-runes-filter').forEach(b=>b.onclick=()=>{shell.querySelectorAll('.yuna-runes-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()});search.oninput=render;render();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
